<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [18 24 30 36 42]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B = Not possible
</pre>

In [112]:
# here A and B are list of lists

def matrix_mul(A, B):
    '''
    This function generates the DOT product of matrices A & B after validating rows and columns of A & B. If the number of  columns in A does not match number of rows in B, then code will not return any DOT product.
    ''' 
    row_A = len(A)
    
    row_B = 0
    col_B = 0
    
    lst_A = []
    for i,row in enumerate(A):
        col_A = 0
        for column in A[i]:
            col_A+=1
        lst_A.append(col_A)
    print("Rows in A: ",row_A)
    print("Columns in A: ",lst_A)
    print()

    lst_B = []
    for j,row in enumerate(B):
        col_B = 0
        row_B+=1
        for column in B[j]:
            col_B+=1
        lst_B.append(col_B)
    print("Rows in B: ",row_B)    
    print("Columns in B: ",lst_B)
    print()


    # ******* START of ROWS and COLUMNS VALIDATION for A and B *******
    
    for i in range(len(lst_A)):
        if(lst_A[i]==row_B): #check if number of A columns = number of B rows
            col_B_chk = 0
            for j in range(len(lst_B)):
                if(lst_B[0]==lst_B[j]): #check if each rows in B has equal number of columns
                    col_B_chk += 1
        else:
            print("Columns in A are NOT EQUAL to rows in B")
            print("A*B = Not possible")
            return

    if(col_B_chk==len(lst_B)):
        print("Columns in all rows are EQUAL in B")
        print("A*B = Possible")
        print()
    else:
        print("Columns in all rows are NOT EQUAL in B")
        print("A*B = Not possible")
        return

    # ******* END of ROWS and COLUMNS VALIDATION for A and B *******


    # ******* START of COLUMN TRANSPOSE in B *******
    '''
        Transpose B to _B for elementwise multiplication
        A = [[1, 3]]

        B = [[1, 2, 3],
             [1, 2, 3]]

        _B = [[1, 1],
              [2, 2],
              [3, 3]]

        Now A * _B = A[0][0] * _B[0][0]
                   = A[0][1] * _B[0][1]
                   = A[0][1] * _B[2][1]

                   can be easily calculated.
    '''

    _B = []
    for i in range(col_B):
        lst = []
        for row in B:
            lst.append(row[i])
        _B.append(lst)
    print("A          ",A)
    print("B Transpose",_B)
    print()

    # ******* END of COLUMN TRANSPOSE in B *******
    
    # ******* START of DOT PRODUCT calculation of A & B *******
    
    # Matrix A*_B
    A_B = []
    A_dot_B = 1
    for i,a_row in enumerate(A):
        Aplus_B = 0
        for j,b_row in enumerate(_B):
            for y,column in enumerate(a_row):
                A_dot_B = A[i][y]*_B[j][y]
                A_B.append(A_dot_B)
    #print("A_B: ",A_B)
    #print("A_B: ",len(A_B))
    #print("row_B",row_B)

    _A_B = []
    for i in range(0,len(A_B),row_B):
        A_plus_B = 0
        for j in range(row_B):
            A_plus_B += A_B[i]
        _A_B.append(A_plus_B)
    print("_A_B: ",_A_B)
    
    AB_temp = []
    AB = []
    i = 0
    j = 0
    slice_len = int(len(_A_B)/row_A)
    slice_temp = slice_len

    while i < row_A:
        #print("row A",row_A)
        #print("i ", i)
        #print("j ", j)
        #print("slice_len", slice_len)
        AB_temp = _A_B[j:slice_len]
        AB.append(AB_temp)
        i +=1
        j += slice_temp
        slice_len += slice_temp

    return(AB)

    # ******* END of DOT PRODUCT calculation of A & B *******


A = [[1, 1, 1], [2, 2, 2], [1, 1, 1], [3, 3, 3]]
B = [[5, 3, 2, 1, 4], 
     [5, 3, 2, 1, 4],
     [5, 3, 2, 1, 4]]

matrix_mul(A, B) # function call

Rows in A:  4
Columns in A:  [3, 3, 3, 3]

Rows in B:  3
Columns in B:  [5, 5, 5]

Columns in all rows are EQUAL in B
A*B = Possible

A           [[1, 1, 1], [2, 2, 2], [1, 1, 1], [3, 3, 3]]
B Transpose [[5, 5, 5], [3, 3, 3], [2, 2, 2], [1, 1, 1], [4, 4, 4]]

_A_B:  [15, 9, 6, 3, 12, 30, 18, 12, 6, 24, 15, 9, 6, 3, 12, 45, 27, 18, 9, 36]


[[15, 9, 6, 3, 12],
 [30, 18, 12, 6, 24],
 [15, 9, 6, 3, 12],
 [45, 27, 18, 9, 36]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [66]:
from random import uniform,choices

'''
with reference from https://pynative.com/python-weighted-random-choices-with-probability/
numberList = [111, 222, 333, 444, 555]
print(choices(numberList, weights=(30,10,0,60,100), k=10))
'''

'''
This function selects an element from the list A randomly with probability proportional to its magnitude
'''

def pick_a_number_from_list(A):
    weighted_list = []
    weighted_tuple = ()
    weight = 10
    A.sort()
    # calculating weigthage for each element in List A => weighted set
    for i in range(len(A)):
        weight*=(i+1)
        weighted_list.append(weight)
        weight = 10
    A.sort(reverse=True)
    weighted_list.sort(reverse=True)
    weighted_tuple = tuple(weighted_list)
    #print("List A: {}, with weight of each elements {}".format(A,weighted_tuple))
    return random.choices(A, weights=weighted_tuple, k=1)

def sampling_based_on_magnitued():
    for i in range(1,20):
        number = pick_a_number_from_list(A)
        print(number)
    return

A = [0, 5, 27, 6, 53, 28, 100, 45, 10, 79]

sampling_based_on_magnitued()


[100]
[79]
[79]
[27]
[100]
[100]
[5]
[100]
[53]
[100]
[53]
[53]
[28]
[100]
[28]
[79]
[5]
[79]
[27]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [1]:
# Code without regex
def replace_digits(String):
    '''
    This function take input of any alpha numeric value and return # for any digits present in the entered string
    '''
    str_list = list(String)
    #print(str_list)
    
    new_list = []
    for index,char in enumerate(str_list):
        if(char in ('0','1','2','3','4','5','6','7','8','9')):
            str_list[index] = '#'
            new_list.append(str_list[index])
    #print(new_list)
    
    modified_str = ''.join(new_list)
    
    return(String, modified_str)
    
    #return # modified string which is after replacing the # with digits

String = input("Please enter any string: ")

String,modified_str = replace_digits(String) #function call

print()
print('Code without regex')
print("Given string: {}, Output: {}".format(String, modified_str))


# Code with regex
import re

def replace_digits_1(String):

    _str_ = re.sub("\D","",String)
    _str_ = re.sub("\d","#",_str_)
    print()
    print('Code with regex')
    print("Given string: {}, Output: {}".format(String, _str_))

replace_digits_1(String) #function call

Please enter any string: 2a$#b%c%561#0

Code without regex
Given string: 2a$#b%c%561#0, Output: #####

Code with regex
Given string: 2a$#b%c%561#0, Output: #####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [2]:
def display_dash_board(students, marks):
    '''
    This function displays 
    a. Students with marks, who got top 5 ranks, in the descending order of marks
    b. Students with marks, who got least 5 ranks, in the increasing order of marks
    d. Students with marks, who got marks between >25th percentile <75th percentile, in the increasing order of marks
    '''
    len_students = len(students)
    len_marks = len(marks)
    #print("students: ",students)
    #print("marks: ",marks)
    temp_list = []
    if(len_students==len_marks):
        orig_list = [[students[i], marks[i]] for i in range(len(students))]
    else:
        ("Data missing")
    
    temp_list = orig_list
    len_temp_list = len(temp_list)

    sorted_list = []
    for index in range(len_students):
        for i in range(len_students-1):
            j = 1
            if(temp_list[i][j] < temp_list[i+1][j]):
                temp = 0
                temp = temp_list[i+1]
                temp_list[i+1] = temp_list[i]
                temp_list[i] = temp
    sorted_list = temp_list
    

    print("All students & marks in descending order: ")
    print()
    for ele in sorted_list:
        print(ele)
    
    Q1_25 = int(len_temp_list/4)
    #print("Q1_25: ",Q1_25)
    Q3_75 = int(len_temp_list*(3/4))
    #print("Q3_75", Q3_75)
    
    # top 5 students
    top_5_students = sorted_list[:5]
    # least 5 students
    least_5_students = sorted_list[-5:]
    least_5_students.reverse()
    # write code for computing top least 5 students
    _temp_list = sorted_list
    _temp_list.reverse()
    students_within_25_and_75 = []
    for i in range(Q1_25,Q3_75):
        students_within_25_and_75.append(_temp_list[i])
    
    return top_5_students, least_5_students, students_within_25_and_75


students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)

print()
print("a. top_5_students: ")
print()
for ele in top_5_students:
    print(ele)
print()
print("b. least_5_students: ")
print()
for ele in least_5_students:
    print(ele)
print()
print("c. students_within_25_and_75: ")
print()
for ele in students_within_25_and_75:
    print(ele)


All students & marks in descending order: 

['student8', 98]
['student10', 80]
['student2', 78]
['student5', 48]
['student7', 47]
['student1', 45]
['student6', 43]
['student9', 35]
['student4', 14]
['student3', 12]

a. top_5_students: 

['student8', 98]
['student10', 80]
['student2', 78]
['student5', 48]
['student7', 47]

b. least_5_students: 

['student3', 12]
['student4', 14]
['student9', 35]
['student6', 43]
['student1', 45]

c. students_within_25_and_75: 

['student9', 35]
['student6', 43]
['student1', 45]
['student7', 47]
['student5', 48]


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [28]:
import math

# here S is list of tuples and P is a tuple of len=2
def closest_points_to_p(S, P):

    temp_list = []
    
    for i in range(len(S)):
        S_num = 0
        P_num = 0
        S_sqr = 1
        P_sqr = 1
        S_into_P = 1
        S_P_plus = 0
        dist = 1
        for j in range(len(P)): # calculation part
            S_sqr = S[i][j]**2
            P_sqr = P[j]**2
            S_num+=S_sqr
            P_num+=P_sqr
            S_into_P = S[i][j] * P[j]
            S_P_plus += S_into_P

        # distance calculation formula
        #dist = 1 / cos((((S[0][0] * P[0]) + (S[0][1] * P[1]))/(sqrt(S[0][0]**2 + S[0][1]**2) * sqrt(P[0]**2 + P[1]**2))))
        
        dist = 1 / (math.cos((S_P_plus) / (math.sqrt(S_num) * math.sqrt(P_num))))
        temp_list.append(dist)
    
    orig_list = [[S[i], temp_list[i]] for i in range(len(S))]
    
    '''
    the below sorting code reference is taken from the link https://www.geeksforgeeks.org/python-list-sort/
    '''
    def sortSecond(val):
        return val[1]

    # sorts the array in ascending according to second element
    orig_list.sort(key = sortSecond, reverse=True)

    closest_5_points = orig_list[:5]

    return  closest_5_points # it's a list of tuples and one element

S = [(1,2),(4,-2),(-1,1),(6,-7),(0,6),(-5,-8),(-1,-1),(6,0),(1,-1),(2,-3)]
P = (3,-4)

points = closest_points_to_p(S, P)
print("Closest 5 points to P = (3,-4)")
print()
for ele in points:
        print(ele) #print the returned values

Closest 5 points to P = (3,-4)

[(2, -3), 1.846390525930369]
[(6, -7), 1.844729420541142]
[(-1, 1), 1.822382959297479]
[(1, -1), 1.822382959297479]
[(4, -2), 1.5975318145459156]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [2]:
import math,re

def i_am_the_one(red,blue,line):
    '''
    This function calculates the perpendicular distance of Red and Blue points for each line equation and verifies,
    if all the Red points are on one side of the line and 
    if all the Blue points are on the other side of the line
    '''
    # string parse to get the coefficients of x,y and intercept
    xyc_val = []
    sub_str = [i for i in re.sub("\+","",line)]
    line = ''.join(sub_str)

    # refered to the below link for the compact for loop and re.split()
    # https://stackoverflow.com/questions/56948506/how-to-extract-coefficients-from-a-line-equation-in-python-without-using-numpy
    xyc_val = [i for i in re.split('[xy]',line)]
    #print(xyc_val)
    
    # calculating perpendicular distance for each Red point for each line equation
    R_list = []
    r_num = 0
    r_deno = 0
    r_perpend_dist = 0
    for r_element in Red:
        r_num = ((float(xyc_val[0])*r_element[0])+(float(xyc_val[1])*r_element[1])+float(xyc_val[2]))
        r_deno = math.sqrt((float(xyc_val[0])**2)+(float(xyc_val[1])**2))
        r_perpend_dist = round((r_num / r_deno),2)
        R_list.append(r_perpend_dist)
    print(R_list)
    
    # calculating perpendicular distance for each Blue point for each line equation
    B_list = []
    b_num = 0
    b_deno = 0
    b_perpend_dist = 0
    for b_element in Blue:
        b_num = ((float(xyc_val[0])*b_element[0])+(float(xyc_val[1])*b_element[1])+float(xyc_val[2]))
        b_deno = math.sqrt((float(xyc_val[0])**2)+(float(xyc_val[1])**2))
        b_perpend_dist = round((b_num / b_deno),2)
        B_list.append(b_perpend_dist)
    print(B_list)

    flag = 0
    for i in range(len(R_list)):
        if((R_list[i] > 0) and (B_list[i] < 0)):
            flag+=1
    if(flag==len(R_list)):
        return "YES"
    else:
        return "NO"


Red= [(1,1),(2,1),(4,2),(2,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i) # the returned value
    print(yes_or_no)
    print()

[1.41, 2.12, 4.24, 4.24]
[-2.12, -2.12, -3.54, -2.83]
YES

[0.0, 0.71, 1.41, -1.41]
[-0.71, 0.71, -0.71, -1.41]
NO

[-2.0, -1.0, 1.0, -1.0]
[-5.0, -4.0, -6.0, -6.0]
NO

[0.5, 0.5, 1.5, 3.5]
[-1.5, -2.5, -2.5, -1.5]
YES



<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [1]:
def curve_smoothing(string):
    '''
    This function reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence
    '''
    
    str_list = string.split(',')
    print("String: ",str_list)
    print()

    # global variables declaration
    dist = 0
    str_len = len(str_list)
    seq_num = 0
    count = 0
    value = 0

    for i in range(0,str_len):
        if(str_list[i]!='_'):
            seq_num +=int(str_list[i])
            count +=1
  
    for index, element in enumerate(str_list):
    
        if(count==0):
            print("Cannot smooth values without a sequence number")
            return
        
        elif(count==1):
            
            # for single sequences like - "125,_,_,_,_"  "_,_,30"  "_,_,100,_,_"
            
            if((str_list[0]!='_' and str_list[str_len-1]=='_') or 
               (str_list[0]=='_' and str_list[str_len-1]!='_') or 
               (str_list[0]=='_' and str_list[str_len-1]=='_')):
                div = str_len
                dist = int(seq_num/div)
                for j in range(index,str_len):
                    str_list[j] = dist
                print("Smoothed_values: ",str_list)
                return
        else:
            
            # for double sequences like - "40,_,_,_,60"
            
            if((str_list[0]!='_' and str_list[str_len-1]!='_') and count==2):
                div = str_len
                dist = int(seq_num/div)
                for j in range(index,str_len):
                    str_list[j] = dist
                print("Smoothed_values: ",str_list)
                return
            
            # for other sequences like - "_,_,30,_,_,_,50,_,_"
            
            else:
                pointer = 0
                for i in range(pointer,str_len):
                    if(str_list[i]!='_'):
                        value = 0
                        if(pointer!=0):
                            div = 0
                            for k in range(pointer,str_len):
                                if(str_list[k]!='_'):
                                    value +=int(str_list[k])
                            div = i - 1
                            dist = int(value/div)
                            for j in range(pointer,int(i)+1):
                                str_list[j] = dist
                            pointer = i
                            cnt = 0
                            for n in range(pointer+1,str_len):
                                if(str_list[i]!='_'):
                                    cnt+=1
                            div=cnt + 1
                            dist = int(int(str_list[pointer])/div)
                            for j in range(pointer,str_len):
                                str_list[j] = dist
                            print("Smoothed_values: ",str_list)
                            return
                        else:      
                            div = int(i)+1
                            value = int(str_list[i])
                            dist = int(value/div)
                            for j in range(int(i)+1):
                                str_list[j] = dist
                            pointer = i


S = "_,_,30,_,_,_,70,_"

curve_smoothing(S) # function call

String:  ['_', '_', '30', '_', '_', '_', '70', '_']

Smoothed_values:  [10, 10, 16, 16, 16, 16, 8, 8]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [144]:
def compute_conditional_probabilites(A):
    '''
    This function will calculate the probability from a martrix of n rows and two columns 
    1. the first column F will contain uniques values e.g. - F1, F2, F3, F4, F5
    2. the second column S will contain uniques values e.g. - S1, S2, S3
    '''

    # global variable declaration
    F_list = []
    S_list = []
    first_position = 0
    second_position = 1

    # separating and generating two lists from A: F_list <= first column , S_list <= second column
    for i in range(len(A)):
        F_list.append(A[i][first_position])
        S_list.append(A[i][second_position])
    first_set = set(F_list) # converting to set to remove duplicate 'F'
    second_set = set(S_list) # converting to set to remove duplicate 'S'
    F_list = list(first_set) # converting to list to use index
    S_list = list(second_set) # converting to list to use index
    F_list.sort()
    S_list.sort()
    
    # joining F_list and S_list => duo_list
    duo_list = []
    for element_1 in F_list:
        temp_list = []
        for element_2 in S_list:
            temp_list = [element_1,element_2]
            duo_list.append(temp_list)

    # comparing the list S with A to find the frequency of elements 'S' => S_count_list
    S_count_list = []
    for i in range(len(S_list)):
        S_count = 0
        temp_list = []
        for j in range(len(A)):
            if(S_list[i]==A[j][second_position]):
                S_count+=1
                temp_list = [S_count,A[j][second_position]]
        S_count_list.append(temp_list)

    # comparing the list A with duo_list to find the frequency => all_list
    all_list = []
    for element_1 in duo_list:
        temp_list = []
        count = 0
        for element_2 in A:
            if(element_1 == element_2):
                count+=1
        temp_list = [element_1,count]
        all_list.append(temp_list)
    
    # comparing all_list & S_count_list to find the probability
    for i in range(len(all_list)):
        for j in range(len(S_count_list)):
            if(all_list[i][first_position][second_position] == S_count_list[j][second_position]):
                print("{} = {}/{}".format(duo_list[i],all_list[i][second_position],S_count_list[j][first_position]))

    return


A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1'],['F5','S3']]


compute_conditional_probabilites(A)

['F1', 'S1'] = 1/4
['F1', 'S2'] = 1/3
['F1', 'S3'] = 0/4
['F2', 'S1'] = 1/4
['F2', 'S2'] = 1/3
['F2', 'S3'] = 1/4
['F3', 'S1'] = 0/4
['F3', 'S2'] = 1/3
['F3', 'S3'] = 1/4
['F4', 'S1'] = 1/4
['F4', 'S2'] = 0/3
['F4', 'S3'] = 1/4
['F5', 'S1'] = 1/4
['F5', 'S2'] = 0/3
['F5', 'S3'] = 1/4


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [54]:
def string_features(S1, S2):
    '''
    This function takes two sentances S1, S2 as input and finds the
    a. Number of common words between S1, S2
    b. Words in S1 but not in S2
    c. Words in S2 but not in S1
    '''
    s1_str = S1.split()
    s2_str = S2.split()

    s1_set = set(s1_str)
    #print("s1: ",s1_set)
    s2_set = set(s2_str)
    #print("s2: ",s2_set)
    
    not_in_s2 = s1_set - s2_set  # Words in S1 but not in S2
    not_in_s1 = s2_set - s1_set  # Words in S2 but not in S1
    
    b = list(not_in_s2)
    c = list(not_in_s1)

    # Number of common words between S1, S2
    a = 0
    for s1_ele in (s1_str):
        for s2_ele in (s2_str):
            if(s1_ele==s2_ele):
                a+=1

    return a, b, c

S1= "The first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"

a,b,c = string_features(S1, S2) # function call
print("a. ",a)
print("b. ",b)
print("c. ",c)

a.  6
b.  ['F', '5', 'The', 'first']
c.  ['S', 'the', '3', 'second']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [70]:
import math

def compute_log_loss(A):
    '''
    This function will calculate the value of f(Y,Y_score) from a martrix of n rows and two columns 
    a. the first column Y will contain interger values
    b. the second column Y_score will have float values
    '''
    all_list = []
    first_position = 0
    second_position = 1

    #generate (1-Y) & (1-Y_score) for each pair of (Y, Y_score) & append it to all_list
    for i in range(len(A)):
        orig_list = []
        orig_list = [A[i][first_position],A[i][second_position]]
        all_list.append(orig_list)
        temp_list = []
        Y = 1 - int(A[i][first_position])
        Y_score = round(1 - float(A[i][second_position]),1)
        temp_list = [Y,Y_score]
        all_list.append(temp_list)
    print("Combined (Y, Y_score) and (1-Y, 1-Y_score) List: ",all_list)
    print()
    
    # log_loss calculation formula
    # f(Y, Y_score) = −1 * 1/n * SUM(Ylog10(Y_score) + ((1-Y)log10(1-Y_score))) <= for each pair of (Y, Y_score)
    sum_Y_log10_Y_score = 0
    for i in range(len(all_list)):
        Y_log10_Y_score = 0
        Y_log10_Y_score = all_list[i][first_position] * math.log10(all_list[i][second_position])
        sum_Y_log10_Y_score += Y_log10_Y_score
    log_loss = -1/int(len(A)) * sum_Y_log10_Y_score
    
    return round(log_loss,7)

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
log_loss = compute_log_loss(A)
print("Log loss: ",log_loss)

Combined (Y, Y_score) and (1-Y, 1-Y_score) List:  [[1, 0.4], [0, 0.6], [0, 0.5], [1, 0.5], [0, 0.9], [1, 0.1], [0, 0.3], [1, 0.7], [0, 0.6], [1, 0.4], [1, 0.1], [0, 0.9], [1, 0.9], [0, 0.1], [1, 0.8], [0, 0.2]]

Log loss:  0.4243099
